2022/11/19/ 21:38:07 PM - INFO - ÂèÇÊï∞ÊâìÂç∞:
2022/11/19/ 21:38:07 PM - INFO - {'apiSec': '5BFasdasdtNg7hwkgCzYQMJSDHDSHD2qOzmtldJasdc'}
2022/11/19/ 21:38:07 PM - INFO - 127.0.0.1 - - [19/Nov/2022 21:38:07] "POST /order HTTP/1.1" 200 -
2022/11/20/ 10:35:25 AM - INFO - 127.0.0.1 - - [20/Nov/2022 10:35:25] "[31m[1mPOST /trade HTTP/1.1[0m" 401 -
2022/11/20/ 10:35:45 AM - INFO - 127.0.0.1 - - [20/Nov/2022 10:35:45] "[31m[1mPOST /trade HTTP/1.1[0m" 401 -
2022/11/20/ 10:35:58 AM - INFO - 127.0.0.1 - - [20/Nov/2022 10:35:58] "[31m[1mPOST /trade HTTP/1.1[0m" 401 -
2022/11/20/ 10:36:30 AM - INFO - 127.0.0.1 - - [20/Nov/2022 10:36:30] "[31m[1mPOST /trade HTTP/1.1[0m" 401 -
2022/11/20/ 10:36:31 AM - INFO - 127.0.0.1 - - [20/Nov/2022 10:36:31] "[31m[1mPOST /trade HTTP/1.1[0m" 401 -
2022/11/20/ 10:37:01 AM - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2022/11/20/ 10:37:01 AM - INFO - [33mPress CTRL+C to quit[0m
2022/11/20/ 10:37:05 AM - INFO - 127.0.0.1 - - [20/Nov/2022 10:37:05] "POST /trade HTTP/1.1" 200 -
2022/11/20/ 10:38:07 AM - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2022/11/20/ 10:38:07 AM - INFO - [33mPress CTRL+C to quit[0m
2022/11/20/ 10:38:12 AM - INFO - 127.0.0.1 - - [20/Nov/2022 10:38:12] "POST /trade HTTP/1.1" 200 -
2022/11/21/ 13:01:40 PM - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2022/11/21/ 13:01:40 PM - INFO - [33mPress CTRL+C to quit[0m
2022/11/21/ 13:01:43 PM - INFO - 127.0.0.1 - - [21/Nov/2022 13:01:43] "[31m[1mPOST /trade HTTP/1.1[0m" 400 -
2022/11/21/ 13:01:59 PM - INFO - 127.0.0.1 - - [21/Nov/2022 13:01:59] "[31m[1mPOST /trade HTTP/1.1[0m" 400 -
2022/11/21/ 13:03:05 PM - INFO - 127.0.0.1 - - [21/Nov/2022 13:03:05] "[31m[1mPOST /trade HTTP/1.1[0m" 400 -
2022/11/21/ 13:03:08 PM - INFO - 127.0.0.1 - - [21/Nov/2022 13:03:08] "[31m[1mPOST /trade HTTP/1.1[0m" 400 -
2022/11/21/ 13:16:25 PM - ERROR - Exception on /trade [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x10250d390>, 'Connection to www.okx.com timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.okx.com', port=443): Max retries exceeded with url: /api/v5/trade/orders-pending?instType=SWAP (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x10250d390>, 'Connection to www.okx.com timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/myway/Desktop/trade_robot_new/trade_okx.py", line 247, in start_trade
    cancel_pending_orders(_instId,"oco")
  File "/Users/myway/Desktop/trade_robot_new/trade_okx.py", line 121, in cancel_pending_orders
    pendingOrders=tradeAPI.get_order_list(instType= _symbolSplit[2])
  File "/Users/myway/Desktop/trade_robot_new/okx/Trade_api.py", line 55, in get_order_list
    return self._request_with_params(GET, ORDERS_PENDING, params)
  File "/Users/myway/Desktop/trade_robot_new/okx/client.py", line 58, in _request_with_params
    return self._request(method, request_path, params)
  File "/Users/myway/Desktop/trade_robot_new/okx/client.py", line 42, in _request
    response = requests.get(url, headers=header)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='www.okx.com', port=443): Max retries exceeded with url: /api/v5/trade/orders-pending?instType=SWAP (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x10250d390>, 'Connection to www.okx.com timed out. (connect timeout=None)'))
2022/11/21/ 13:16:25 PM - INFO - 127.0.0.1 - - [21/Nov/2022 13:16:25] "[35m[1mPOST /trade HTTP/1.1[0m" 500 -
2022/11/21/ 13:16:42 PM - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2022/11/21/ 13:16:42 PM - INFO - [33mPress CTRL+C to quit[0m
2022/11/21/ 13:18:00 PM - ERROR - Exception on /trade [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x104d780a0>, 'Connection to www.okx.com timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.okx.com', port=443): Max retries exceeded with url: /api/v5/trade/orders-pending?instType=SWAP (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x104d780a0>, 'Connection to www.okx.com timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/myway/Desktop/trade_robot_new/trade_okx.py", line 248, in start_trade
    cancel_pending_orders(_instId,"oco")
  File "/Users/myway/Desktop/trade_robot_new/trade_okx.py", line 121, in cancel_pending_orders
    pendingOrders=tradeAPI.get_order_list(instType= _symbolSplit[2])
  File "/Users/myway/Desktop/trade_robot_new/okx/Trade_api.py", line 55, in get_order_list
    return self._request_with_params(GET, ORDERS_PENDING, params)
  File "/Users/myway/Desktop/trade_robot_new/okx/client.py", line 58, in _request_with_params
    return self._request(method, request_path, params)
  File "/Users/myway/Desktop/trade_robot_new/okx/client.py", line 42, in _request
    response = requests.get(url, headers=header)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='www.okx.com', port=443): Max retries exceeded with url: /api/v5/trade/orders-pending?instType=SWAP (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x104d780a0>, 'Connection to www.okx.com timed out. (connect timeout=None)'))
2022/11/21/ 13:18:00 PM - INFO - 127.0.0.1 - - [21/Nov/2022 13:18:00] "[35m[1mPOST /trade HTTP/1.1[0m" 500 -
2022/11/21/ 13:18:31 PM - INFO - 127.0.0.1 - - [21/Nov/2022 13:18:31] "POST /trade HTTP/1.1" 200 -
2022/11/21/ 13:40:35 PM - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2022/11/21/ 13:40:35 PM - INFO - [33mPress CTRL+C to quit[0m
2022/11/21/ 13:41:18 PM - INFO - ËØ∑Ê±ÇÂèÇÊï∞Ôºö
2022/11/21/ 13:41:18 PM - INFO - {'apiSec': '5BFasdasdtNg7hwkgCzYQMJSDHDSHD2qOzmtldJasdc', 'symbol': 'BTC-USDT-SWAP', 'amount': '0.1', 'type': 'market', 'side': 'buy', 'price': '', 'tdMode': 'isolated', 'level': '5', 'enable_stop_loss': False, 'enable_stop_gain': False, 'slTriggerPx': '', 'tpTriggerPx': ''}
2022/11/21/ 13:41:18 PM - INFO - ÂáÜÂ§áÂºÄ‰ªì
2022/11/21/ 13:41:29 PM - INFO - ÂΩìÂâçÊú™Êàê‰∫§ÁöÑËÆ¢Âçï:
2022/11/21/ 13:41:29 PM - INFO - {'code': '0', 'data': [], 'msg': ''}
2022/11/21/ 13:41:29 PM - INFO - {'code': '0', 'data': [], 'msg': ''}
2022/11/21/ 13:41:33 PM - INFO - {'code': '0', 'data': [{'acctLv': '2', 'autoLoan': False, 'ctIsoMode': 'automatic', 'greeksType': 'PA', 'level': 'Lv1', 'levelTmp': '', 'liquidationGear': '-1', 'mgnIsoMode': 'automatic', 'posMode': 'net_mode', 'roleType': 0, 'spotOffsetType': '', 'traderInstruments': [], 'uid': '148380495300960256'}], 'msg': ''}
2022/11/21/ 13:41:33 PM - INFO - Ë¥¶Êà∑ÁöÑÊåÅ‰ªìÊ®°Âºè:
2022/11/21/ 13:41:33 PM - INFO - net_mode
2022/11/21/ 13:41:33 PM - INFO - ÂçïÂêëÊ®°ÂºèÂπ≥‰ªì:
2022/11/21/ 13:41:40 PM - INFO - {'code': '0', 'data': [{'clOrdId': '', 'instId': 'BTC-USDT-SWAP', 'posSide': 'net', 'tag': ''}], 'msg': ''}
2022/11/21/ 13:41:44 PM - INFO - ËÆæÁΩÆË¥¶Êà∑ÁöÑÊåÅ‰ªìÊ®°Âºè:
2022/11/21/ 13:41:44 PM - INFO - {'code': '0', 'data': [{'posMode': 'net_mode'}], 'msg': ''}
2022/11/21/ 13:41:47 PM - INFO - ÂºÄÁöÑÊù†ÊùÜÂÄçÊï∞:
2022/11/21/ 13:41:47 PM - INFO - {'code': '0', 'data': [{'instId': 'BTC-USDT-SWAP', 'lever': '5', 'mgnMode': 'isolated', 'posSide': ''}], 'msg': ''}
2022/11/21/ 13:41:49 PM - INFO - {'code': '0', 'data': [{'instId': 'BTC-USDT-SWAP', 'px': '', 'sz': '100', 'type': '1', 'unit': 'coin'}], 'msg': ''}
2022/11/21/ 13:41:49 PM - INFO - Â∏ÅÂº†ËΩ¨Êç¢:
2022/11/21/ 13:41:52 PM - INFO - ‰∏ãÂçï‰ø°ÊÅØÔºö
2022/11/21/ 13:41:52 PM - INFO - {'code': '0', 'data': [{'clOrdId': '', 'ordId': '514797600973885440', 'sCode': '0', 'sMsg': 'Order successfully placed', 'tag': ''}], 'msg': ''}
2022/11/21/ 13:41:52 PM - INFO - 127.0.0.1 - - [21/Nov/2022 13:41:52] "POST /trade HTTP/1.1" 200 -
